### ISSUE TITLE
VFP9.zip link to ISO - Download Problems

### ISSUE THREAD

**Issue by RickStrahl** [VFPX/VFPInstallers#1]
It looks like renaming the ISO to a ZIP file causes problems with the download - Edge won't let you download it unless you explicitly tell it to in the download drop down (which is very hard to notice unless you know what you're looking for). The reason for this likely is that the file is not recognized as a valid ZIP file.

Since this is a direct download anyway one of two things would probably work better:

* **Raw ISO file**   
This is probably the better solution as this won't bloat the size.  ISO files may be flagged as dangerous too, but it can't be any worse than what browsers are doing to the Zip file 😄 

*  **Zip the ISO**   
This won't actually reduce the size, but if you think for packaging to use Zip then this at least will be a legit ZIP file. I think though at that point you still get the same issue you would as the raw ISO as the scanner peeks inside of the ZIP for the content.

Given all that I think the raw ISO is probably the best solution, and potentially adding a second zip link for those that can't download an ISO directly (due to enterprise policy).

ps.

Thank you for setting up this repo and for adding the VFP.ISO file. I get so many people contacting me where to find a copy of Visual FoxPro for re-install (and also to purchase - no solution for that though).

**Comment by DougHennig** [comment]
I was hoping to serve it as vfp9.iso so I created a MIME type for *.iso as application/octet-stream but still get a 404 when trying to access it. Is there something I'm missing? That's why I went with the renaming.

I took your suggestion and zipped the ISO but I still get the same "vfp9.zip cannot be downloaded securely" issue when I click the link, likely because the site doesn't have a cert and I'm using http:// not https://. Interesting, if you paste the link (http://vfpxrepository.com/files/vfp9.zip) into the browser address bar, no such warning.

**Comment by rschummer** [comment]
@RickStrahl 

FYI, if you need to refer people to purchase VFP 9, there is still a location for North Americans at https://store.forwardthinkingsoftware.com/Catalog/Tools when bundled with Visual Extend (VFX). 

Devs on other continents can get it direct from Rainer: 
Phone ++49-6173-950903, Fax ++49-6173-950904
http://www.visualextend.com/
bestellungen@dfpug.de

Also still included in MSDN Subscription from Microsoft.

**Comment by RickStrahl** [comment]
Rick's previous comment might make for good information in the Readme file @DougHennig...

Couple of related things I thought of:

* VFP Runtime Installers pointing to this repo
* Back link from here back to Runtime Installers

**Comment by DougHennig** [comment]
@RickStrahl Already done. This repo has all installers. I didn't remove the Runtime Installers repo in case folks have a link to it but it's basically deprecated.

**Comment by RickStrahl** [comment]
@DougHennig I'm guessing the 404 comes from the IIS Request filtering. You probably have to bump up the allowed download size in the request filtering.

![image](https://user-images.githubusercontent.com/1374013/206840964-03a0183f-e5d4-44c8-baaf-8341eaa99133.png)


Looks like the default is 30mb which is not enough for the ISO download (says it's 34,2mb)

**Comment by DougHennig** [comment]
You can now download the ISO directly. There were two issues:

- The control panel my web hosting company uses has a bug: adding a MIME type adds it without the "*.". I fixed that using IIS Manager so the ISO is now recognized.
- I added a Let's Encrypt cert to the site and changed the link to HTTPS so Edge no longer complains about not downloading the file securely.
