### ISSUE TITLE
64 bit ODBC driver?

### ISSUE THREAD

**Issue by carlhunt3r** [VFPX/VFPInstallers#2]
Is there a 64 bit ODBC driver available for foxpro?

**Comment by DougHennig** [comment]
No.

**Comment by carlhunt3r** [comment]
Hi @DougHennig, do you know of a way to access a FoxPro database from a 64 bit ODBC software? Scenario is Azure Data Factory's integration runtime is only a 64 bit architecture. I'm even struggling to even find a 3rd party ODBC.

**Comment by DougHennig** [comment]
There used to be a 64-bit driver from Advantage but it's long since discontinued.
